### ISSUE TITLE
Trouble installing nodebots-interchange with npm

### ISSUE THREAD

**Issue by noidwasavailable** [nodebots/nodebots-interchange#41]
When I try to install the module, I get the following timeout error:

```
> npm install -g nodebots-interchange                                 
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t git://github.com/ajfisher/avrgirl-arduino.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 52.78.231.108]: errno=Operation timed out
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/csharp/.npm/_logs/2019-12-03T15_22_55_940Z-debug.log
```

I managed to install directly by
```
> git clone https://github.com/johnny-five-io/nodebots-interchange.git
npm install
```

but even with that, "interchange" is not recognized by my zsh. 
How do I go about fixing it?

**Comment by ajfisher** [comment]
@noidwasavailable  this may be because of your `path` variable. When you install it either globally or locally, you'll need to ensure your path makes the command line `interchange` file available.

You can add the global `node_modules` on your path however usually I just add `./node_modules/.bin` to my path instead - basically giving me access to all the command line tools that have been installed into my project (this gives me flexibility with different versions of things between projects etc as well).

**Comment by ajfisher** [comment]
@noidwasavailable did you get any more info about this? If it's not an issue any more then I'll go ahead and close this out.

**Comment by ajfisher** [comment]
This should be solved by the new version 2 that has just released so I'm going to close this out. Please reopen if there's any issues.
